export const INDIA_STATE_DISTRICTS: Record<string, string[]> = {
  "Andhra Pradesh": [
    "Anantapur",
    "Chittoor",
    "East Godavari",
    "Eluru",
    "Guntur",
    "Kadapa",
    "Kakinada",
    "Kurnool",
    "Nellore",
    "Prakasam",
    "Srikakulam",
    "Tirupati",
    "Visakhapatnam",
    "Vizianagaram",
    "West Godavari",
  ],
  "Arunachal Pradesh": [
    "Changlang",
    "East Siang",
    "Itanagar Capital Complex",
    "Lohit",
    "Lower Subansiri",
    "Namsai",
    "Papum Pare",
    "Tawang",
    "Tirap",
    "West Kameng",
  ],
  Assam: [
    "Barpeta",
    "Cachar",
    "Dibrugarh",
    "Goalpara",
    "Golaghat",
    "Jorhat",
    "Kamrup Metropolitan",
    "Nagaon",
    "Sivasagar",
    "Sonitpur",
    "Tinsukia",
  ],
  Bihar: [
    "Begusarai",
    "Bhagalpur",
    "Bhojpur",
    "Darbhanga",
    "Gaya",
    "Muzaffarpur",
    "Nalanda",
    "Patna",
    "Purnia",
    "Samastipur",
  ],
  Chhattisgarh: [
    "Bilaspur",
    "Durg",
    "Janjgir-Champa",
    "Korba",
    "Raigarh",
    "Raipur",
    "Rajnandgaon",
    "Surguja",
  ],
  Goa: ["North Goa", "South Goa"],
  Gujarat: [
    "Ahmedabad",
    "Anand",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Kutch",
    "Mehsana",
    "Rajkot",
    "Surat",
    "Vadodara",
  ],
  Haryana: [
    "Ambala",
    "Faridabad",
    "Gurugram",
    "Hisar",
    "Karnal",
    "Kurukshetra",
    "Panipat",
    "Rohtak",
    "Sonipat",
    "Yamunanagar",
  ],
  "Himachal Pradesh": [
    "Bilaspur",
    "Chamba",
    "Hamirpur",
    "Kangra",
    "Kullu",
    "Mandi",
    "Shimla",
    "Solan",
    "Una",
  ],
  Jharkhand: [
    "Bokaro",
    "Deoghar",
    "Dhanbad",
    "Dumka",
    "East Singhbhum",
    "Hazaribagh",
    "Palamu",
    "Ranchi",
    "West Singhbhum",
  ],
  Karnataka: [
    "Ballari",
    "Belagavi",
    "Bengaluru Rural",
    "Bengaluru Urban",
    "Dakshina Kannada",
    "Dharwad",
    "Kalaburagi",
    "Mysuru",
    "Shivamogga",
    "Udupi",
  ],
  Kerala: [
    "Alappuzha",
    "Ernakulam",
    "Idukki",
    "Kannur",
    "Kasaragod",
    "Kollam",
    "Kottayam",
    "Kozhikode",
    "Malappuram",
    "Palakkad",
    "Pathanamthitta",
    "Thiruvananthapuram",
    "Thrissur",
    "Wayanad",
  ],
  "Madhya Pradesh": [
    "Bhopal",
    "Chhindwara",
    "Gwalior",
    "Indore",
    "Jabalpur",
    "Khandwa",
    "Rewa",
    "Sagar",
    "Satna",
    "Ujjain",
  ],
  Maharashtra: [
    "Ahmednagar",
    "Amravati",
    "Aurangabad",
    "Jalgaon",
    "Kolhapur",
    "Mumbai City",
    "Mumbai Suburban",
    "Nagpur",
    "Nanded",
    "Nashik",
    "Pune",
    "Raigad",
    "Satara",
    "Solapur",
    "Thane",
  ],
  Manipur: [
    "Bishnupur",
    "Churachandpur",
    "Imphal East",
    "Imphal West",
    "Senapati",
    "Tamenglong",
    "Thoubal",
    "Ukhrul",
  ],
  Meghalaya: [
    "East Garo Hills",
    "East Jaintia Hills",
    "East Khasi Hills",
    "Ri-Bhoi",
    "West Garo Hills",
    "West Jaintia Hills",
    "West Khasi Hills",
  ],
  Mizoram: [
    "Aizawl",
    "Champhai",
    "Kolasib",
    "Lawngtlai",
    "Lunglei",
    "Mamit",
    "Serchhip",
  ],
  Nagaland: [
    "Dimapur",
    "Kohima",
    "Mokokchung",
    "Mon",
    "Phek",
    "Tuensang",
    "Wokha",
    "Zunheboto",
  ],
  Odisha: [
    "Balasore",
    "Cuttack",
    "Ganjam",
    "Khordha",
    "Koraput",
    "Mayurbhanj",
    "Puri",
    "Sambalpur",
    "Sundargarh",
  ],
  Punjab: [
    "Amritsar",
    "Bathinda",
    "Firozpur",
    "Hoshiarpur",
    "Jalandhar",
    "Ludhiana",
    "Pathankot",
    "Patiala",
    "SAS Nagar (Mohali)",
  ],
  Rajasthan: [
    "Ajmer",
    "Alwar",
    "Bharatpur",
    "Bikaner",
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Pali",
    "Sikar",
    "Udaipur",
  ],
  Sikkim: ["Gangtok", "Gyalshing", "Mangan", "Namchi", "Pakyong", "Soreng"],
  "Tamil Nadu": [
    "Ariyalur",
    "Chengalpattu",
    "Chennai",
    "Coimbatore",
    "Cuddalore",
    "Dharmapuri",
    "Dindigul",
    "Erode",
    "Kallakurichi",
    "Kanchipuram",
    "Kanyakumari",
    "Karur",
    "Krishnagiri",
    "Madurai",
    "Mayiladuthurai",
    "Nagapattinam",
    "Namakkal",
    "Nilgiris",
    "Perambalur",
    "Pudukottai",
    "Ramanathapuram",
    "Ranipet",
    "Salem",
    "Sivaganga",
    "Tenkasi",
    "Thanjavur",
    "Theni",
    "Thoothukudi",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tirupathur",
    "Tiruppur",
    "Tiruvallur",
    "Tiruvannamalai",
    "Tiruvarur",
    "Vellore",
    "Viluppuram",
    "Virudhunagar",
  ],
  Telangana: [
    "Adilabad",
    "Hanamkonda",
    "Hyderabad",
    "Karimnagar",
    "Khammam",
    "Mahabubnagar",
    "Medak",
    "Nalgonda",
    "Nizamabad",
    "Rangareddy",
    "Siddipet",
    "Warangal",
  ],
  Tripura: [
    "Dhalai",
    "Gomati",
    "Khowai",
    "North Tripura",
    "Sepahijala",
    "South Tripura",
    "Unakoti",
    "West Tripura",
  ],
  "Uttar Pradesh": [
    "Agra",
    "Aligarh",
    "Ayodhya",
    "Bareilly",
    "Gautam Buddha Nagar",
    "Ghaziabad",
    "Gorakhpur",
    "Jhansi",
    "Kanpur Nagar",
    "Lucknow",
    "Meerut",
    "Moradabad",
    "Prayagraj",
    "Varanasi",
  ],
  Uttarakhand: [
    "Almora",
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Pauri Garhwal",
    "Pithoragarh",
    "Tehri Garhwal",
    "Udham Singh Nagar",
  ],
  "West Bengal": [
    "Darjeeling",
    "Hooghly",
    "Howrah",
    "Kolkata",
    "Malda",
    "Murshidabad",
    "Nadia",
    "North 24 Parganas",
    "Paschim Bardhaman",
    "Purba Bardhaman",
    "South 24 Parganas",
  ],
  "Andaman and Nicobar Islands": ["Nicobar", "North and Middle Andaman", "South Andaman"],
  Chandigarh: ["Chandigarh"],
  "Dadra and Nagar Haveli and Daman and Diu": ["Dadra and Nagar Haveli", "Daman", "Diu"],
  Delhi: [
    "Central Delhi",
    "East Delhi",
    "New Delhi",
    "North Delhi",
    "North East Delhi",
    "North West Delhi",
    "Shahdara",
    "South Delhi",
    "South East Delhi",
    "South West Delhi",
    "West Delhi",
  ],
  "Jammu and Kashmir": [
    "Anantnag",
    "Baramulla",
    "Budgam",
    "Doda",
    "Jammu",
    "Kathua",
    "Kulgam",
    "Kupwara",
    "Pulwama",
    "Rajouri",
    "Samba",
    "Srinagar",
    "Udhampur",
  ],
  Ladakh: ["Kargil", "Leh"],
  Lakshadweep: ["Kavaratti"],
  Puducherry: ["Karaikal", "Mahe", "Puducherry", "Yanam"],
};

export const INDIA_STATES = Object.keys(INDIA_STATE_DISTRICTS);

export function getDistrictsByState(state: string): string[] {
  return INDIA_STATE_DISTRICTS[state] ?? [];
}
